# -*- coding: utf-8 -*-
"""Cluster_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhQG_hJRTysjixpyWzoedf48_nXfXuls
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
#Generate synthetic dataset
X, y_true = make_blobs(n_samples=500,centers=4,cluster_std=1.2,random_state=42)
print("Feature matrix shape:", X.shape)
print("True labels shape:", y_true.shape)

class KMeansScratch:
    def __init__(self, n_clusters=4, max_iters=100):
        self.n_clusters = n_clusters
        self.max_iters = max_iters
    def fit(self, X):
        np.random.seed(42)

        # Randomly choose initial centroids
        random_idx = np.random.choice(len(X), self.n_clusters, replace=False)
        self.centroids = X[random_idx]
        for _ in range(self.max_iters):
            # Step 1: Assign clusters
            distances = np.linalg.norm(X[:, np.newaxis] - self.centroids, axis=2)
            self.labels = np.argmin(distances, axis=1)

            # Step 2: Recalculate centroids
            new_centroids = np.array([X[self.labels == k].mean(axis=0)
                                      for k in range(self.n_clusters)])

            # Step 3: Check convergence
            if np.allclose(self.centroids, new_centroids):
                break

            self.centroids = new_centroids

        return self

    def predict(self, X):
        distances = np.linalg.norm(X[:, np.newaxis] - self.centroids, axis=2)
        return np.argmin(distances, axis=1)

kmeans_scratch = KMeansScratch(n_clusters=4)
kmeans_scratch.fit(X)

labels_scratch = kmeans_scratch.labels
centroids_scratch = kmeans_scratch.centroids
kmeans_sklearn = KMeans(n_clusters=4,random_state=42,n_init=10)
labels_sklearn = kmeans_sklearn.fit_predict(X)
centroids_sklearn = kmeans_sklearn.cluster_centers_
sil_scratch = silhouette_score(X, labels_scratch)
sil_sklearn = silhouette_score(X, labels_sklearn)

print("Silhouette Score (Scratch K-Means):", sil_scratch)
print("Silhouette Score (Scikit-learn KMeans):", sil_sklearn)
print("Final Centroids (Scratch K-Means):")
print(centroids_scratch)

print("\nFinal Centroids (Scikit-learn KMeans):")
print(centroids_sklearn)

plt.figure(figsize=(8,6))
plt.scatter(X[:, 0], X[:, 1], c=labels_scratch, alpha=0.6,cmap='viridis')
plt.scatter(centroids_scratch[:, 0],centroids_scratch[:, 1],marker='o',s=40,c='black', edgecolors='k')
plt.title("Scratch K-Means Clustering")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()